language: node_js
node_js:
  - "6.10"
sudo: required  
dist: trusty 
branches:
  only:
    - master
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g @angular/cli
script:
  - ng test --single-run --code-coverage
  #- ng build --prod --aot=false
after_script:
  # https://www.gregjs.com/javascript/2016/how-to-get-a-shiny-coverage-badge-for-your-github-project/
  - cat ./coverage/lcov.info | node node_modules/.bin/coveralls 
notifications:
  email:
    on_failure: change
    on_success: change